Repository microsoft/fhir-proxy, pull requests merged in 2021-06, with the labels that each got.

#8 Documentation updates
  README.md
  SUPPORT.md
  docs/INSTALL.md
  docs/SUPPORT.md
  docs/addingappsvcprincipals.md
  docs/addingusers.md
  docs/configuration.md
  docs/images/change-deployment-cntr1.png
  docs/images/change-deployment-cntr2.png
  docs/images/change-deployment-cntr3.png
  docs/images/default-setup.png
  docs/images/deployment-cntr-logs.png
  docs/images/proxy-env.png
  docs/updating-fhir-proxy.md
Labels: documentation

#10 Azure quickstart - ARM/ bicep deployment templates and documentation
  azure-quickstart/azuredeploy.bicep
  azure-quickstart/azuredeploy.json
  azure-quickstart/azuredeploy.parameters.json
  azure-quickstart/fhirroles.json
  azure-quickstart/registerproxy.bash
  docs/QuickstartDeployARM-bicep.md
  docs/images/Azure_Portal_Screenshot_10_resize.png
  docs/images/Azure_Portal_Screenshot_11_resize.png
  docs/images/Azure_Portal_Screenshot_12_resize.png
  docs/images/Azure_Portal_Screenshot_13_resize.png
  docs/images/Azure_Portal_Screenshot_14_resize.png
  docs/images/Azure_Portal_Screenshot_15_resize.png
  docs/images/Azure_Portal_Screenshot_16_resize.png
  docs/images/Azure_Portal_Screenshot_17_resize.png
  docs/images/Azure_Portal_Screenshot_18_resize.png
  docs/images/Azure_Portal_Screenshot_19_resize.png
  docs/images/Azure_Portal_Screenshot_1_resize.png
  docs/images/Azure_Portal_Screenshot_20_resize.png
  docs/images/Azure_Portal_Screenshot_2_resize.png
  docs/images/Azure_Portal_Screenshot_3_resize.png
  docs/images/Azure_Portal_Screenshot_4_resize.png
  docs/images/Azure_Portal_Screenshot_5_resize.png
  docs/images/Azure_Portal_Screenshot_6_resize.png
  docs/images/Azure_Portal_Screenshot_7_resize.png
  docs/images/Azure_Portal_Screenshot_8_resize.png
  docs/images/Azure_Portal_Screenshot_9_resize.png
  docs/images/addascope.png
  docs/images/oauth2permissionsattribs.png
  docs/images/selectAAD.png
  docs/images/selectAppregistration.png
  docs/images/selectexposeapi.png
  docs/images/selectproxyreg.png
Labels: documentation, enhancement

#11 SMART on FHIR Auth, scope, and App config documentation
  docs/Configuration-of-SMARTonFHIR-auth.md
  docs/Setup-SMARTonFHIR-App-documentation.md
  docs/images/addascope_resize.png
  docs/images/oauth2permissionsattribs_resize.png
  docs/images/selectAAD_resize.png
  docs/images/selectAppregistration_resize.png
  docs/images/selectexposeapi_resize.png
  docs/images/selectproxyreg_resize.png
  docs/images/smart_on_fhir_1.png
  docs/images/smart_on_fhir_10.png
  docs/images/smart_on_fhir_11.png
  docs/images/smart_on_fhir_12.png
  docs/images/smart_on_fhir_13.png
  docs/images/smart_on_fhir_2.png
  docs/images/smart_on_fhir_3.png
  docs/images/smart_on_fhir_4.png
  docs/images/smart_on_fhir_5.png
  docs/images/smart_on_fhir_6.png
  docs/images/smart_on_fhir_7.png
  docs/images/smart_on_fhir_8.png
  docs/images/smart_on_fhir_9.png
Labels: documentation

#12 CLI install with azure tags
  scripts/deployfhirproxy.bash
Labels: enhancement

#15 Documentation Corrections
  docs/Configuration-of-SMARTonFHIR-auth.md
  docs/QuickstartDeployARM-bicep.md
  docs/Setup-SMARTonFHIR-App-documentation.md
  docs/images/Azure_Portal_Screenshot_10_resize.png
  docs/images/Azure_Portal_Screenshot_11_resize.png
  docs/images/Azure_Portal_Screenshot_12_resize.png
  docs/images/Azure_Portal_Screenshot_13_resize.png
  docs/images/Azure_Portal_Screenshot_14_resize.png
  docs/images/Azure_Portal_Screenshot_15_resize.png
  docs/images/Azure_Portal_Screenshot_16_resize.png
  docs/images/Azure_Portal_Screenshot_17_resize.png
  docs/images/Azure_Portal_Screenshot_18_resize.png
  docs/images/Azure_Portal_Screenshot_19_resize.png
  docs/images/Azure_Portal_Screenshot_1_resize.png
  docs/images/Azure_Portal_Screenshot_20_resize.png
  docs/images/Azure_Portal_Screenshot_2_resize.png
  docs/images/Azure_Portal_Screenshot_3_resize.png
  docs/images/Azure_Portal_Screenshot_4_resize.png
  docs/images/Azure_Portal_Screenshot_5_resize.png
  docs/images/Azure_Portal_Screenshot_6_resize.png
  docs/images/Azure_Portal_Screenshot_7_resize.png
  docs/images/Azure_Portal_Screenshot_8_resize.png
  docs/images/Azure_Portal_Screenshot_9_resize.png
  docs/images/smart/addascope.png
  docs/images/smart/addascope_resize.png
  docs/images/smart/oauth2permissionsattribs.png
  docs/images/smart/oauth2permissionsattribs_resize.png
  docs/images/smart/selectAAD.png
  docs/images/smart/selectAAD_resize.png
  docs/images/smart/selectAppregistration.png
  docs/images/smart/selectAppregistration_resize.png
  docs/images/smart/selectexposeapi.png
  docs/images/smart/selectexposeapi_resize.png
  docs/images/smart/selectproxyreg.png
  docs/images/smart/selectproxyreg_resize.png
  docs/images/smart/smart_on_fhir_1.png
  docs/images/smart/smart_on_fhir_10.png
  docs/images/smart/smart_on_fhir_11.png
  docs/images/smart/smart_on_fhir_12.png
  docs/images/smart/smart_on_fhir_13.png
  docs/images/smart/smart_on_fhir_2.png
  docs/images/smart/smart_on_fhir_3.png
  docs/images/smart/smart_on_fhir_4.png
  docs/images/smart/smart_on_fhir_5.png
  docs/images/smart/smart_on_fhir_6.png
  docs/images/smart/smart_on_fhir_7.png
  docs/images/smart/smart_on_fhir_8.png
  docs/images/smart/smart_on_fhir_9.png
  docs/images/update/change-deployment-cntr1.png
  docs/images/update/change-deployment-cntr2.png
  docs/images/update/change-deployment-cntr3.png
  docs/images/update/default-setup.png
  docs/images/update/deployment-cntr-logs.png
  docs/images/update/proxy-env.png
  docs/updating-fhir-proxy.md
  templates/azuredeploy.bicep
  templates/azuredeploy.json
  templates/azuredeploy.parameters.json
  templates/fhirroles.json
  templates/registerproxy.bash
Labels: documentation
